name: WakaTime Readme Stats Update

on:
  schedule:
    # Runs every day at 12am UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with WakaTime stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WakaTime Readme Stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: "true"         # Optional: Show the title "WakaTime Stats"
          SHOW_LANGUAGE: "true"      # Optional: Show most used languages
          SHOW_EDITORS: "true"       # Optional: Show editors used
          SHOW_OS: "true"            # Optional: Show Operating System used
          SHOW_PROJECTS: "true"      # Optional: Show most used projects
